image: python:3.13-slim  # Use a fresh Python container

stages:
  - install
  - test
  - deploy
  - sshcheck

install:
  stage: install
  tags:
    - macos
  script:
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements.txt
  artifacts:
    paths:
      - venv/

test:
  stage: test
  tags:
    - macos
  script:
    - python -m pip install pytest
    - pytest || echo "Tests failed or not found"

ssh-test:
  stage: sshcheck
  tags:
    - macos
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H ec2-35-181-170-203.eu-west-3.compute.amazonaws.com >> ~/.ssh/known_hosts
  script:
    - ssh ubuntu@ec2-35-181-170-203.eu-west-3.compute.amazonaws.com "hostname"

deploy:
  stage: deploy
  tags:
    - macos
  script:
    - echo "Deploying application..."
    - echo "Deployment complete!"
  only:
    - main
